name: Rodrigo Vinicius Blog
description: Programming
meta_description: "Blog pessoal de desenvolvimento e programação"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /kasper
domain_name: "https://https://rodrigovvo.github.io/"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://rodrigovvo.github.io/"
author: "Rodrigo Vinicius"

# Disqus config
disqus-shortname: ""
